### ISSUE TITLE
[질문] 6045번 문제 오류 아닌가요

### ISSUE THREAD

**Issue by pwjdgus** [CodeUp100Challenge/CodeUp100_Challenge#4]
'''
정수 3개를 입력받아 합과 평균을 출력해보자.

참고
공백으로 구분된 한 줄로 값들을 입력받기 위해서는
a, b, c = input().split()
과 같은 방법이 가능하고,

공백으로 구분해 두 값을 출력하기 위해서는
print(d, e)
와 같은 방법이 가능하다.

잘라낸 값들은 그 값의 특성(정수, 실수, 문자, 문자열 ...)에 따라 명확하게 변환시킨 후 사용하는 것이 좋다.

python 프로그래밍을 처음 배울 때 좋은 습관(단계)
1. 입력된 문자열을 정확하게 잘라낸다.(공백, 줄바꿈, 구분문자 등에 따라 정확하게 잘라낸다.)
2. 잘라낸 데이터들을 데이터형에 맞게 변환해 변수에 저장한다. (정수, 실수, 문자, 문자열 등에 따라 정확하게 변환한다.)
3. 값을 저장했다가 다시 사용하기 위해, 변수를 이용해 값을 저장하고, 변수를 이용해 계산을 한다.
4. 원하는 결과 값을 필요한 형태로 만들어 출력한다.(공백, 줄바꿈, 구분자, 등에 따라 원하는 형태로 만들어 출력한다.)
'''

입력 : 공백을 가지고 숫자 3개 입력
출력 : 합과 평균을 공백을 두고 출력한다. 평균은 소숫점 이하 셋째 자리에서 반올림하여 둘째 자리까지 출력한다.

내 코드 
~~~py
a, b, c = list(map(int, input().split()))
sum = a+b+c
avg =float(sum)/3.0
print(sum, round(avg, 2))
~~~

output : 6 2.0

**Comment by a0Kim** [comment]
제 코드는 이거입니다. 
~~~py
a,b,c=map(int,input().split())
sum=a+b+c
avg=sum/3
print(sum,format(avg,".2f"))
~~~

<img width="450" alt="6045번" src="https://user-images.githubusercontent.com/94776040/149728541-514d6a8c-9933-48f4-a91b-bf6e60778e6c.png">

format 함수는 반올림 안되는 줄 알았으나 해보니까 반올림이 됩니다 . @pwjdgus 님처럼 왜 round함수를 썼을때, 답이 2.0만 나오는지는 저도 궁금합니다.

**Comment by pwjdgus** [comment]
```round()```의 경우 소수점 뒤 쓸모없는 0을 제거하고 출력한다고 합니다.
```format()```을 이용해서 풀걸 그랬네요

지금 보니까 제 코드 음주 코딩인 것 같네요 ㅋㅋ
